title: <p align="center"> Veronika Moroz </p>

logo: "/images/me.jpg?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/veronika-moroz-664448107/">LinkedIn</a> |
  <a href="https://github.com/vpetrova13">GitHub</a> |
  <a href="https://twitter.com/veronikapetr13">Twitter</a>
  </p>
  
  <p align="justify">
  Hi! My name is Veronika and I am beginner in data industry. 
  <br><br>
  After graduating with Data Analysis course from CodeClan, I'm looking to start a new career in the data industry, with the hope to learn and grow as a professional in this field.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
